apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config

data:
  DB_NAME: {{ .Values.mysql.database | quote }}
  DB_USER: {{ .Values.mysql.user | quote }}
  DB_PORT: {{ .Values.mysql.service.port | quote }}
  DB_HOST: "db"
