apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-django

spec:
  selector:
    app: {{ .Release.Name }}-django

  ports:
    - name: http
      port: 8000
      targetPort: http

  type: ClusterIP
