apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-nginx

spec:
  selector:
    app: {{ .Release.Name }}-nginx

  ports:
    - name: http
      port: {{ .Values.nginx.service.port }}
      targetPort: http
      nodePort: {{ .Values.nginx.service.nodePort }}

  type: {{ .Values.nginx.service.type }}
