
django:
  replicaCount: 2

  image:
    repository: avinashkharate/django-app
    tag: latest
    pullPolicy: Always

  service:
    port: 8000
    



mysql:
  image:
    repository: mysql
    tag: "8.0"

  database: test_db
  user: root
  password: root

  service:
    port: 3306

  persistence:
    size: 5Gi


nginx:
  image:
    repository: avinashkharate/notes-nginx
    tag: latest
    pullPolicy: Always

  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 31796

  upstream:
    host: notes-app-django
    port: 8000
